### ISSUE TITLE
Getting Errors 

### ISSUE THREAD

**Issue by cyberbloke** [GH0st3rs/YahooFinance#2]
I just downloaded the files and tried to run and getting the following issues:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./stock_yahoo.py", line 128, in <module>
    main()
  File "./stock_yahoo.py", line 123, in main
    resp = requests.get(URL, data).json()['quoteResponse']['result']
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] Forbidden: 0

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Platform : LInuxMint 20.3
Kernel:     Custom Kernel 5.17.1
Python:    Python 3.8 
JSON:      jq-1.6

Thanks

**Comment by GH0st3rs** [comment]
Yahoo started checking the User-Agent and the old request returned a 403 error. I fixed it, try again

**Comment by cyberbloke** [comment]
Thank you very much for such a prompt response to my request.  

Thanks and with warm regards.


-  
E: ***@***.***
P: +1-301-500-0918(tel:+1-301-500-0918)
